name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    name: Build Job
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

  deploy_job:
    runs-on: windows-latest
    needs: build_job
    steps:
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: fb31e2a31eda3b9300d6631f255182bf82603ec039c57052ab03d8c63a748abd5-58c3ec95-86da-4237-99ae-8f27c4847015010468037
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"  # Assicura che il percorso sia correttamente configurato
          output_location: "frontend-tyb/build"  # Assicura che il percorso di output sia corretto
